In [1]:
import pandas as pd

In [2]:
df_silver = pd.read_csv(f"2_bronze/bronze_cripto_180d.csv")

In [3]:
df_silver.info()
df_silver.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   code         6 non-null      object
 1   codein       6 non-null      object
 2   name         6 non-null      object
 3   high         1004 non-null   float64
 4   low          1004 non-null   float64
 5   varBid       1004 non-null   float64
 6   pctChange    1004 non-null   float64
 7   bid          1004 non-null   float64
 8   ask          1004 non-null   float64
 9   timestamp    1004 non-null   int64
 10  create_date  6 non-null      object
 11  moeda        1004 non-null   object
dtypes: float64(6), int64(1), object(5)
memory usage: 94.3+ KB

,code,codein,name,high,low,varBid,pctChange,bid,ask,timestamp,create_date,moeda
0,BTC,BRL,Bitcoin/Real Brasileiro,600175.0,591450.0,4911.0,0.825,600089.0,600090.0,1749406859,2025-06-08 15:20:59,BTC
1,NaN,NaN,NaN,595999.0,584270.0,7445.0,1.269,594061.0,594062.0,1749340785,NaN,BTC
2,NaN,NaN,NaN,593914.0,568693.0,15804.0,2.769,586639.0,586640.0,1749254379,NaN,BTC
3,NaN,NaN,NaN,596717.0,563594.0,-22105.0,-3.728,570835.0,570836.0,1749167992,NaN,BTC
4,NaN,NaN,NaN,600910.0,589040.0,-4640.0,-0.777,592871.0,592872.0,1749081575,NaN,BTC

In [4]:
df_silver.columns

Index(['code', 'codein', 'name', 'high', 'low', 'varBid', 'pctChange', 'bid',
       'ask', 'timestamp', 'create_date', 'moeda'],
      dtype='object')

In [5]:
# Excluir colunas que não serão utilizadas:

df_silver.drop(columns=['code', 'codein','name','create_date'], inplace=True)

In [6]:
# renomeando as colunas para ficar mais claro as informações:

colunas_renomeadas = {
    'high': 'preco_maximo',
    'low': 'preco_minimo',
    'varBid': 'variacao_bid',
    'pctChange': 'variacao_pct',
    'bid': 'preco_compra',
    'ask': 'preco_venda',
    'timestamp': 'data_hora',
    'moeda': 'moeda'
}
df_silver.rename(columns=colunas_renomeadas, inplace=True)

In [7]:
# Adicionando a nomenclatura para ficar mais claro o tipo de cotação (código Cripto + código real):

df_silver['moeda'] = df_silver['moeda'] + '-BRL'

In [8]:
# Conversão do formato de data e hora da coluna 'data_hora' (segundos -> data + hora

df_silver['data_hora'] = pd.to_datetime(df_silver['data_hora'], unit='s')
df_silver['data_hora'] = df_silver['data_hora'].dt.strftime('%d/%m/%Y %H:%M')

In [9]:
df_silver.info()
df_silver.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   preco_maximo  1004 non-null   float64
 1   preco_minimo  1004 non-null   float64
 2   variacao_bid  1004 non-null   float64
 3   variacao_pct  1004 non-null   float64
 4   preco_compra  1004 non-null   float64
 5   preco_venda   1004 non-null   float64
 6   data_hora     1004 non-null   object
 7   moeda         1004 non-null   object
dtypes: float64(6), object(2)
memory usage: 62.9+ KB

,preco_maximo,preco_minimo,variacao_bid,variacao_pct,preco_compra,preco_venda,data_hora,moeda
0,600175.0,591450.0,4911.0,0.825,600089.0,600090.0,08/06/2025 18:20,BTC-BRL
1,595999.0,584270.0,7445.0,1.269,594061.0,594062.0,07/06/2025 23:59,BTC-BRL
2,593914.0,568693.0,15804.0,2.769,586639.0,586640.0,06/06/2025 23:59,BTC-BRL
3,596717.0,563594.0,-22105.0,-3.728,570835.0,570836.0,05/06/2025 23:59,BTC-BRL
4,600910.0,589040.0,-4640.0,-0.777,592871.0,592872.0,04/06/2025 23:59,BTC-BRL
5,606034.0,596533.0,-5413.0,-0.898,597511.0,597512.0,03/06/2025 23:59,BTC-BRL
6,609322.0,592144.0,-4675.0,-0.769,602924.0,602925.0,02/06/2025 23:59,BTC-BRL
7,608849.0,599500.0,3763.0,0.623,607553.0,607554.0,01/06/2025 23:59,BTC-BRL
8,606305.0,596143.0,2882.0,0.480,603708.0,603709.0,31/05/2025 23:59,BTC-BRL
9,607704.0,594944.0,-2008.0,-0.333,600801.0,600802.0,30/05/2025 23:59,BTC-BRL

In [10]:
# Salvando arquivo na camada silver

df_silver.to_csv("3_silver/silver_cripto_180d.csv", index=False)